export const LOADING_AUTH = "LOADING_AUTH";
export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_ERROR = "LOGOUT_ERROR";

export const CREATE_TALK_SUCCESS = "CREATE_TALK_SUCCESS";
export const CREATE_TALK_ERROR = "CREATE_TALK_ERROR";
export const FETCH_TALKS_SUCCESS = "FETCH_TALKS_SUCCESS";
export const FETCH_TALKS_ERROR = "FETCH_TALKS_ERROR";
export const DELETE_TALK_SUCCESS = "DELETE_TALK_SUCCESS";
export const DELETE_TALK_ERROR = "DELETE_TALK_ERROR";

export const CREATE_ATTENDEE_SUCCESS = "CREATE_ATTENDEE_SUCCESS";
export const CREATE_ATTENDEE_ERROR = "CREATE_ATTENDEE_ERROR";
export const FETCH_ATTENDEES_SUCCESS = "FETCH_ATTENDEES_SUCCESS";
export const FETCH_ATTENDEES_ERROR = "FETCH_ATTENDEES_ERROR";
export const DELETE_ATTENDEE_SUCCESS = "DELETE_ATTENDEE_SUCCESS";
export const DELETE_ATTENDEE_ERROR = "DELETE_ATTENDEE_ERROR";